/*****************************************************************************
*           : 
*           :     Copyright (c) 1993-94 by Alexey V. Papin. 
*           :   This information may not be changed or copyed 
*           :       without special permission of author. 
*           : 
* Name      : AS_CHECK     
* Describe  : проверка на наличие в директории файлов
* File      : C:\ALEX\WORK\AS_CHECK.C        
* Last edit : 14.08.93 01.02.16
* Remarks   : 
*****************************************************************************/

void check (asList far *list,int dx);
/***********
* Describe : отмечает имеющиеся в директории файлы
* Params   : asList far *list - список имен записей
*          : int dx           - сколько из списка проверять
* Return   : void
* Call     : 
***********/