/*****************************************************************************
*           :
*           :     Copyright (c) 1993-94 by Alexey V. Papin.
*           :   This information may not be changed or copyed
*           :       without special permission of author.
*           :
* Name      : AS_DIAG
* Describe  : диагностика
* File      : C:\ALEX\WORK\AS_DIAG.C
* Last edit : 14.08.93 01.05.12
* Remarks   :
*****************************************************************************/

char *diagnoze (char *fname,char *field);
/***********
* Describe : выдача диагностического сообщения о параметре из БД
* Params   : char *fname - имя БД
*          : char *field - имя параметра
* Return   : char        - сообщение
* Call     : 
***********/