/*****************************************************************************
*           :
*           :     Copyright (c) 1993-94 by Alexander Golovnev
*           :   This information may not be changed or copyed
*           :       without special permission of author.
*           :
* Name      : M_EXPORT
* Describe  : Преобразование формата .spe в текстовый файл
* File      : C:\ALEX\WORK\M_EXPORT.C
* Last edit : 18.12.94 00.57.17
* Remarks   :
*****************************************************************************/

void export (void);
/***********
* Describe : Выбор записей из файла формата  .spe и запись в файл .spt в текст.виде
* Params   : 
*          : 
*          : 
*          : 
* Return   : void
* Call     :
***********/
