/*****************************************************************************
*           : 
*           :     Copyright (c) 1993-94 by Alexey V. Papin. 
*           :   This information may not be changed or copyed 
*           :       without special permission of author. 
*           : 
* Name      : M_PRINT     
* Describe  : 
* File      : C:\ALEX\WORK\M_PRINT.H        
* Last edit : 30.06.93 01.05.52
* Remarks   : 
*****************************************************************************/

void print (void);
void quality (void);
void setmargin(void);
void setport (void);
void height (void);