/*****************************************************************************
*           : 
*           :     Copyright (c) 1993-94 by Alexey V. Papin. 
*           :   This information may not be changed or copyed 
*           :       without special permission of author. 
*           : 
* Name      : M_QUIT     
* Describe  : 
* File      : C:\ALEX\WORK\M_QUIT.H        
* Last edit : 02.07.93 02.46.01
* Remarks   : 
*****************************************************************************/

void quit (void);
/***********
* Describe : 
* Params   : void
* Return   : void
* Call     : 
***********/

void beforequit (void);
/***********
* Describe : 
* Params   : void
* Return   : void
* Call     : 
***********/