/*****************************************************************************
*           :
*           :     Copyright (c) 1993-94 by Alexey V. Papin.
*           :   This information may not be changed or copyed
*           :       without special permission of author.
*           :
* Name      : AS_3D
* Describe  : Трехмерная графика
* File      : C:\ALEX\WORK\AS_3D.C
* Last edit : 14.08.93 00.57.17
* Remarks   :
*****************************************************************************/

void graph3D (int y1,int y2,asFile far *files,int num);
/***********
* Describe : 
* Params   : int y1
*          : int y2
*          : asFile far *files
*          : int num
* Return   : void
* Call     : 
***********/