/*****************************************************************************
*           : 
*           :     Copyright (c) 1993-94 by Alexey V. Papin. 
*           :   This information may not be changed or copyed 
*           :       without special permission of author. 
*           : 
* Name      : AS_CAPTU     
* Describe  : Запись граф. копии экрана в файл
* File      : C:\ALEX\WORK\AS_CAPTU.C        
* Last edit : 14.08.93 00.59.52
* Remarks   : 
*****************************************************************************/

void capture_screen (void);
/***********
* Describe : записать экран на диск
* Params   : void
* Return   : void
* Call     : 
***********/