/*****************************************************************************
*           :
*           :     Copyright (c) 1993-94 by Alexey V. Papin.
*           :   This information may not be changed or copyed
*           :       without special permission of author.
*           :
* Name      : AS_MSG
* Describe  : Определения сообщений
* File      : C:\ALEX\WORK\AS_MSG.H
* Last edit : 30.06.93 00.53.55
* Remarks   :
*****************************************************************************/

extern const char *errNoMemory[];
extern const char *errNoFiles[] ;
extern const char *errNoTime [];
extern const char *errFormFile[];
extern const char *errNoHelp[]  ;

extern const char *slMain    ;
extern const char *slControl ;
extern const char *slRecord  ;
extern const char *slCascade ;
extern const char *slOptions ;
extern const char *slPrint   ;
extern const char *slGraph   ;
extern const char *sl3DGraph ;
extern const char *sldbGraph ;
extern const char *slChFtime ;
extern const char *slChFtimes;
extern const char *slChFile  ;
extern const char *slChField ;
extern const char *slReceive ;

extern char *msgMaxTime[]  ;
extern char *msgEscape[]   ;
extern char *msgNoItems[]  ;
extern char *msgImgSize[]  ;
extern char *msgNoImgMem[] ;
extern char *msgMkDir[]    ;
extern char *msgReceive[]  ;
extern char *msgSig[]      ;
extern char *msgLog[]      ;  
extern char *msgLin[]      ;
extern char *msgFFTSpe[]   ;
extern char *msgFFTSig[]   ; 
extern char *msgNoDif[]    ;
extern char *msgNoInt[]    ;