/*****************************************************************************
*           :
*           :     Copyright (c) 1993-94 by Alexey V. Papin.
*           :   This information may not be changed or copyed
*           :       without special permission of author.
*           :
* Name      : AS_MAIN
* Describe  : Заголовочный файл главного модуля программы
* File      : C:\ALEX\WORK\AS_MAIN.H
* Last edit : 18.07.93 00.29.59
* Remarks   :
*****************************************************************************/

void main (int argc,char *argv[]);
void destroy_program (void);
char *fullpath (char *p);