/*****************************************************************************
*           : 
*           :     Copyright (c) 1993-94 by Alexey V. Papin. 
*           :   This information may not be changed or copyed 
*           :       without special permission of author. 
*           : 
* Name      : AS_OTHER     
* Describe  : 
* File      : C:\ALEX\WORK\AS_OTHER.C        
* Last edit : 14.08.93 01.08.49
* Remarks   : 
*****************************************************************************/

void loadname (char *fname);
/***********
* Describe : загpузка записи из файла .spe по имени и вpемени записи
* Params   : void
* Return   : void
* Call     : choosefile,chooseftime,incorrect,setframe,killframe,load,
*          : statusline,graphwindow,loading
***********/